Preparation view component
equinor/fusion-bmt pull request #104
Opened 2020-11-09 11:02 UTC by tmals-equi

2020-11-09 15:49 UTC, nicholasdalhaug requested changes
I think some of my comments here are important for not making the integration with the backend a really big job. I also see some Codacy messages that we might want fixed.

2020-11-09 15:49 UTC, nicholasdalhaug commented on frontend/src/views/PreparationView.tsx
> +    title: string
```suggestion
    barrier: Barrier
```

2020-11-09 15:49 UTC, nicholasdalhaug commented on frontend/src/views/PreparationView.tsx
> +const BarrierQuestions = ({title, questions}: BarrierQuestionsProps) => {
Could we rather call this something like 

```suggestion
const BarrierQuestionsView = ({barrier, questions}: BarrierQuestionsViewProps) => {
```

Or `Form` if that is more appropriate?

2020-11-09 15:49 UTC, nicholasdalhaug commented on frontend/src/views/PreparationView.tsx
> +            <h2>{title}</h2>
Should we rather use eds `Typography`here?

```suggestion
            <Typography variant="h2">{title}</Typography>
```

2020-11-09 15:49 UTC, nicholasdalhaug commented on frontend/src/views/PreparationView.tsx
> +                        <hr style={{ height: "1", color: "lightgray" }}/>
Is there no divider in Fusion or EDS to use instead?

2020-11-09 15:49 UTC, nicholasdalhaug commented on frontend/src/views/PreparationView.tsx
> +                    <>
Every dynamically generated list should have a key prop in react

2020-11-09 15:49 UTC, nicholasdalhaug commented on frontend/src/views/PreparationView.tsx
> +                            answer={question.answers[0]}
There should be some filtering here to only view the answers from the user, if it is not guaranteed from the backend. By this I mean that we should remove the magic indexing `[0]` in some way.

2020-11-09 15:49 UTC, nicholasdalhaug commented on frontend/src/views/PreparationView.tsx
> +                            questionNumber={1}
The question number should probably be generated dynamically.

2020-11-09 15:49 UTC, nicholasdalhaug commented on frontend/src/views/PreparationView.tsx
> +const BarrierQuestions = ({title, questions}: BarrierQuestionsProps) => {
I also think that this could be moved to its own file.

2020-11-09 15:49 UTC, nicholasdalhaug commented on frontend/src/views/PreparationView.tsx
> +                aside: <Chip title="3/10" />
This number should be generated from the questions and answers

2020-11-09 15:49 UTC, nicholasdalhaug commented on frontend/src/views/PreparationView.tsx
> +                />
Can we move this together with some of the code above into its own component and even its own file?

2020-11-09 15:49 UTC, nicholasdalhaug commented on frontend/src/views/PreparationView.tsx
> +                <div style={{margin: 20}}>
We could do 
```suggestion
            <Box m={20}>
```
here, but how about we just stick to one method and use the MUI `Container`?

2020-11-09 15:49 UTC, nicholasdalhaug commented on frontend/src/views/PreparationView.tsx
> +                    <BarrierQuestions title={selectedBarrier} questions={evaluation.questions.filter(q => q.barrier === selectedBarrier)} />
I think we should have some nicer formatting of this long line. 

```suggestion
                    <BarrierQuestions 
                        title={selectedBarrier} 
                        questions={
                            evaluation.questions.filter(
                                q => q.barrier === selectedBarrier
                            )
                        } 
                    />
```
It does not need to be this split up, but maybe more than it is?

2020-11-09 16:08 UTC, tmals-equi commented on frontend/src/views/PreparationView.tsx
> +                <div style={{margin: 20}}>
Hmm, I'm not sure how you reproduce this behaviour with Container?

2020-11-10 12:06 UTC, nicholasdalhaug approved these changes
Looks very good to me!

2020-11-10 12:07 UTC, merged