Add graphql-codegen for generating ts models
equinor/fusion-bmt pull request #115
Opened 2020-11-10 17:50 UTC by ReedOnly

closes #103

2020-11-12 10:43 UTC, nicholasdalhaug requested changes

2020-11-12 10:43 UTC, nicholasdalhaug commented on backend/api/Models/Models.cs
> +        [Description("General Matters")]
Are these descriptions doing anything?

2020-11-12 10:43 UTC, nicholasdalhaug commented on doc/schema.graphql
> +schema {
Shouldn't this file be autogenerated? And if so, should it be removed from the repo?

2020-11-12 10:43 UTC, nicholasdalhaug commented on frontend/schema.yml
> +# schema: ../doc/schema.graphql
I see the value of this comment for debugging. Maybe we should consider adding it to the readme instead?

2020-11-12 10:43 UTC, nicholasdalhaug commented on frontend/src/api/models.ts
> +};
The Input types such as these I think are redundant. I do not think they are used, maybe we should get rid of them?There are also some other types here that are not used and we do not want to maintain.

2020-11-12 10:43 UTC, nicholasdalhaug commented on frontend/src/api/modelsCustom.ts
> +export type Action = {
I guess we can remove this file as well? What is it for?

2020-11-12 10:43 UTC, nicholasdalhaug commented on frontend/src/components/QuestionAndAnswer/QuestionAndAnswerForm.tsx
> +                            severity={answer.severity || Severity.Na}
I think we should rather enforce severity to be set than to check for undefined everywhere.

2020-11-12 10:43 UTC, nicholasdalhaug commented on frontend/src/components/QuestionAndAnswer/QuestionAndAnswerForm.tsx
> +    const [markdown, setMarkdown] = useState<string>(answer.text || "");
Same as below. We should enforce it to be defined.

2020-11-12 12:28 UTC, ReedOnly commented on doc/schema.graphql
> +schema {
Yes, it was until I had the file from server working

2020-11-12 12:28 UTC, ReedOnly commented on backend/api/Models/Models.cs
> +        [Description("General Matters")]
No, we can remove

2020-11-12 12:28 UTC, ReedOnly commented on frontend/schema.yml
> +# schema: ../doc/schema.graphql
think for now we can just remove

2020-11-12 12:29 UTC, ReedOnly commented on frontend/src/api/modelsCustom.ts
> +export type Action = {
The old manual file. Will remove

2020-11-12 12:30 UTC, ReedOnly commented on frontend/src/components/QuestionAndAnswer/QuestionAndAnswerForm.tsx
> +                            severity={answer.severity || Severity.Na}
Will fix in backend

2020-11-12 12:30 UTC, ReedOnly commented on frontend/src/components/QuestionAndAnswer/QuestionAndAnswerForm.tsx
> +    const [markdown, setMarkdown] = useState<string>(answer.text || "");
yes

2020-11-13 10:56 UTC, nicholasdalhaug commented on frontend/package.json
> +        "schema": "graphql-codegen --config schema.yml"
Could this file be moved to api, next to the models.ts?

2020-11-13 10:56 UTC, nicholasdalhaug commented on frontend/src/api/models.ts
> -}
I think we should fix everywhere that this is used before merging to master. This we change the barrier dialog/sidesheet. Or at least make an issue on the board for fixing it with the highest priority.

2020-11-13 10:56 UTC, nicholasdalhaug commented on frontend/schema.yml
> +      maybeValue: T
Is it possible to have a comment here about what this does?

2020-11-13 10:56 UTC, nicholasdalhaug commented on frontend/src/api/models.ts
> +};
If we cannot remove these I really hope we do not get much problems from the typescript definitions. It can be difficult to get the correct typescript when it is based on C# and has to go through 2 layers of transpiling.

2020-11-13 11:07 UTC, ReedOnly commented on frontend/src/api/models.ts
> -}
Will make an Issue to the board

2020-11-13 11:11 UTC, ReedOnly commented on frontend/schema.yml
> +      maybeValue: T
done

2020-11-13 11:40 UTC, nicholasdalhaug approved these changes

2020-11-13 11:47 UTC, merged