Evaluation list
equinor/fusion-bmt pull request #118
Opened 2020-11-11 12:37 UTC by tmals-equi

2020-11-16 14:26 UTC, nicholasdalhaug requested changes

2020-11-16 14:26 UTC, nicholasdalhaug commented on backend/api/Services/ProjectService.cs
> +                .Include(project => project.Evaluations)
This should not be necessary anymore, right?

2020-11-16 14:26 UTC, nicholasdalhaug commented on frontend/src/views/Project/Dashboard/EvaluationListItem.tsx
> +    }
This function should be made simpler. Maybe some reusability as well. How about a function from currentProgression and progressionToCheck called `checkProgressionStatus` which returns a progression status of `In Progress`, `Completed` or `Awaiting`? That function is then testable as well. Then simply use that function in this component.

2020-11-16 14:26 UTC, nicholasdalhaug commented on frontend/src/views/Project/Dashboard/EvaluationListItem.tsx
> +                />
I think we should make a new component here that itself figures out if the symbol should be a check of a clock, like in the Figma sketches. And maybe also finds out its own color depending on the input.

2020-11-16 14:26 UTC, nicholasdalhaug commented on frontend/src/views/Project/Dashboard/ProjectDashboardGQL.ts
> +                                    projectId
Have you checked that his works and that you do not need to use the same fragment as in the query for the caching to work?

2020-11-16 14:26 UTC, nicholasdalhaug commented on frontend/src/views/Project/Dashboard/ProjectDashboardGQL.ts
> +                projectId
You can also reuse the newly created fragment here.

2020-11-16 14:26 UTC, nicholasdalhaug commented on frontend/src/views/Project/Dashboard/ProjectDashboardGQL.ts
> +            evaluations(where: {projectId: {eq: "${projectId}"}}) {
I think that using projectId like this is not ideal. We should rather do queries like GraphQL suggests by referring to the property `project`. See `Nesting your objects in queries` [here](https://atheros.ai/blog/graphql-best-practices-for-graphql-schema-design).

2020-11-16 14:26 UTC, nicholasdalhaug commented on frontend/src/views/Project/Dashboard/ProjectDashboardView.tsx
> +                value={`Error in loading participants: ${JSON.stringify(errorQuery)}`}
I think there might be some copy-paste error here and same below.

2020-11-16 14:28 UTC, tmals-equi commented on backend/api/Services/ProjectService.cs
> +                .Include(project => project.Evaluations)
Why not?

2020-11-17 08:20 UTC, nicholasdalhaug commented on backend/api/Services/ProjectService.cs
> +                .Include(project => project.Evaluations)
Because you are not fetching the evaluation by getting the evaluation under project. You  should get the evaluation from the evaluations query and filter on the underlying project.

2020-11-17 09:13 UTC, tmals-equi commented on backend/api/Services/ProjectService.cs
> +                .Include(project => project.Evaluations)
Yeah true, but do we know we'll never do it like that?

2020-11-17 14:17 UTC, nicholasdalhaug commented on frontend/src/views/Project/Dashboard/ProjectDashboardGQL.ts
> +            evaluations(where: {projectId: {eq: "${projectId}"}}) {
```suggestion
            evaluations(where: {project: {id: {eq: "${projectId}"}}}) {
```

2020-11-18 12:48 UTC, nicholasdalhaug commented on backend/api/Services/ProjectService.cs
> +using Microsoft.EntityFrameworkCore;
I think you can remove this import.

2020-11-18 12:48 UTC, nicholasdalhaug commented on frontend/src/routes/ProjectRoute.tsx
> +                id,
Maybe we do not need commas here?

2020-11-18 13:37 UTC, nicholasdalhaug approved these changes

2020-11-18 13:42 UTC, merged