DB context tests
equinor/fusion-bmt pull request #126
Opened 2020-11-16 13:06 UTC by Christdej

2020-11-16 14:33 UTC, nicholasdalhaug requested changes

2020-11-16 14:33 UTC, nicholasdalhaug commented on backend/tests/DbContext.cs
> +            Assert.True(participantsBefore + 1 == participantsAfter);
We get a better output from testing if we use `Assert.Equals` instead. Same farther down.

2020-11-16 14:33 UTC, nicholasdalhaug commented on backend/tests/DbContext.cs
> +            int participantsBefore = exampleEvaluation.Participants.Count;
I think a newline right here, to follow the AAA(Arrange, Act, Assert) pattern would be nice.

2020-11-16 14:33 UTC, nicholasdalhaug commented on backend/tests/DbContext.cs
> +            ParticipantService participantService = new ParticipantService(_context);
The participant service could be initialized before the int, thereby also using the AAA(Arrange, Act, Assert) pattern.

2020-11-17 07:38 UTC, Christdej commented on backend/tests/DbContext.cs
> +            Assert.True(participantsBefore + 1 == participantsAfter);
Good point, will fix =)

2020-11-17 07:39 UTC, Christdej commented on backend/tests/DbContext.cs
> +            int participantsBefore = exampleEvaluation.Participants.Count;
Done

2020-11-17 07:39 UTC, Christdej commented on backend/tests/DbContext.cs
> +            ParticipantService participantService = new ParticipantService(_context);
Done

2020-11-17 13:42 UTC, ReedOnly approved these changes

2020-11-17 14:11 UTC, nicholasdalhaug approved these changes

2020-11-18 07:37 UTC, merged