Delete nominee button
equinor/fusion-bmt pull request #142
Opened 2020-11-18 13:46 UTC by tmals-equi

2020-11-19 17:33 UTC, nicholasdalhaug requested changes
Nice! I just have a few comments.

2020-11-19 17:33 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/Nomination/NominationTable.tsx
> +    <ParticipantCard key={item.participant.id} participant={item.participant} />
We. do not need this anymore, right? We just tested it. There was an other solution.

2020-11-19 17:33 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/Nomination/NominationTable.tsx
> +const DeleteColumn: React.FC<DataTableRowProps> = ({ item }) => {
Could we call this something like (?)
```suggestion
const DeleteColumnItemRenderer: React.FC<DataTableRowProps> = ({ item }) => {
```

We should anyways call the two renderers something similar.

2020-11-19 17:33 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/Nomination/NominationTable.tsx
> +    if (item.role === Role.Facilitator) return null
Could we return a react fragment instead? 
```suggestion
    if (item.role === Role.Facilitator) return <></>
```

2020-11-19 17:33 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/Nomination/NominationTable.tsx
> +}
Could the content of this be moved to a new file or something. Especially since this does a call to the backend, I think it might be nice to not hide that inside this complex file for DataTable abstraction.

2020-11-19 17:33 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/Nomination/NominationTable.tsx
> +    progressionStatus: ProgressionStatus
Is it better to call it (?)
```suggestion
    currentProgressionStatus: ProgressionStatus
```

2020-11-23 12:12 UTC, tmals-equi commented on frontend/src/views/Evaluation/Nomination/NominationTable.tsx
> +}
I'm not sure I think that's necessary for such a small component. Also, then we'd need to either define the DataTableRowProps twice, since both DeleteColumnItemRenderer and DataTableItemRenderer use it

2020-11-24 11:46 UTC, nicholasdalhaug approved these changes

2020-11-24 11:57 UTC, merged