Enum to string
equinor/fusion-bmt pull request #149
Opened 2020-11-23 14:24 UTC by tmals-equi

2020-11-23 16:19 UTC, nicholasdalhaug requested changes

2020-11-23 16:19 UTC, nicholasdalhaug commented on frontend/src/utils/EnumToString.ts
> +        return ""
Why do we need default?

```suggestion
```

2020-11-23 16:19 UTC, nicholasdalhaug commented on frontend/src/utils/EnumToString.ts
> +let OrganizationToString = (organization: Organization): string => {
Same as above: const , lower case and no default? Same below as well.

2020-11-24 13:24 UTC, ReedOnly approved these changes

2020-11-24 13:47 UTC, merged