Answer summary
equinor/fusion-bmt pull request #158
Opened 2020-11-25 10:31 UTC by tmals-equi

2020-12-01 16:17 UTC, nicholasdalhaug requested changes
I think it would be nice to have a more condensed summary form, like in the figma sketches.

2020-12-01 16:17 UTC, nicholasdalhaug commented on frontend/src/components/BarrierQuestionsView.tsx
> +    onQuestionSummarySelected: (question: Question) => void
Maybe remove the redundant prop?

```suggestion
    onQuestionSummarySelected?: (question: Question) => void
```

2020-12-01 16:17 UTC, nicholasdalhaug commented on frontend/src/components/AnswerSummarySidebar.tsx
> +const AnswerSummarySidebar = ({ open, onCloseClick, question }: AnswerSummarySidebarProps) => {
I think it needs to know what progression we are on. We do not want the preparation answers to come up in the workshop.

2020-12-01 16:17 UTC, nicholasdalhaug commented on frontend/src/components/BarrierQuestionsView.tsx
> +                            onQuestionSummarySelected={onQuestionSummarySelected}
I do not like that we have to pass props a long way down, but I am not sure how we can fix it either. Could some context providers be helpful? Or maybe creating new components instead of changing the ones that exist.

2020-12-01 16:17 UTC, nicholasdalhaug commented on frontend/src/components/SeverityIndicator.tsx
> +    let getColor = (severity: Severity) => {
```suggestion
    const getColor = (severity: Severity) => {
```

2020-12-01 16:17 UTC, nicholasdalhaug commented on frontend/src/components/SingleAnswerSummary.tsx
> +    let apiClients = useApiClients()
```suggestion
    const apiClients = useApiClients()
```

2020-12-01 16:17 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/Alignment/AlignmentView.tsx
> +            }
Since the form has an `open` prop, we do not need the nesting. Then we will not get messages about unable to render unmounted component, although they are hard to see among all our other warnings. 

```suggestion
            <AnswerSummarySidebar
                open={selectedQuestion != undefined}
                onCloseClick={() => { setSelectedQuestion(undefined) }}
                question={selectedQuestion} 
            />
```

2020-12-02 09:13 UTC, tmals-equi commented on frontend/src/components/BarrierQuestionsView.tsx
> +    onQuestionSummarySelected: (question: Question) => void
Yeah, I was thinking about this too. But that means deciding if the button is visible based on whether or not that prop is defined. I like that, but I can also see it could be confusing, what do you think?

2020-12-02 11:10 UTC, nicholasdalhaug commented on frontend/src/components/BarrierQuestionsView.tsx
> +    onQuestionSummarySelected: (question: Question) => void
Otherwise there will be a coupling between those two props. I think it seems better like you just suggested.

2020-12-02 12:04 UTC, tmals-equi commented on frontend/src/components/AnswerSummarySidebar.tsx
> +                <Typography variant="h3">{question.text}</Typography>
Yep, I wanted to have it, but it's not trivial to add, because the number seems to be resolved simply by the index during iteration, and that happens in a component further down than this.

2020-12-02 12:06 UTC, tmals-equi commented on frontend/src/components/BarrierQuestionsView.tsx
> +    onQuestionSummarySelected: (question: Question) => void
:+1:

2020-12-07 12:24 UTC, nicholasdalhaug requested changes

2020-12-07 12:24 UTC, nicholasdalhaug commented on frontend/src/components/QuestionAndAnswer/QuestionAndAnswerFormWithApi.tsx
> +    const azureUniqueId = getAzureUniqueId()
It does not look like this is used.

2020-12-07 12:24 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/Alignment/AlignmentView.tsx
> +import { useQuestionsQuery } from '../Preparation/PerparationGQL'
The code in preparationgql should probably be moved up one level if it is used here as well.

2020-12-07 12:24 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/Alignment/AlignmentView.tsx
> +import { useQuestionsQuery } from '../Preparation/PerparationGQL'
But I have removed this in my latest code, so that we get the questions from the evaluation query. Maybe we do not need to fix this here, then?

2020-12-07 12:42 UTC, tmals-equi commented on frontend/src/views/Evaluation/Alignment/AlignmentView.tsx
> +import { useQuestionsQuery } from '../Preparation/PerparationGQL'
OK, if you have removed it then I think it should be fine for now

2020-12-07 13:48 UTC, nicholasdalhaug approved these changes

2020-12-07 13:48 UTC, merged