Fix env variable issue when deploying to fusion CI
equinor/fusion-bmt pull request #249
Opened 2021-01-05 18:19 UTC by ReedOnly

2021-01-08 14:16 UTC, nicholasdalhaug commented
Should this be a draft PR until fusion has updated its package? Then we can install the new package and this PR can be merged.

2021-01-13 10:20 UTC, ReedOnly commented
https://pro-s-portal-ci.azurewebsites.net/apps/bmt

2021-01-13 11:45 UTC, nicholasdalhaug requested changes

2021-01-13 11:45 UTC, nicholasdalhaug commented on frontend/resources/app-icon.svg
> +<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
Could this resources folder be combined with what we have as the docs folder? If it is not simple, we do not need to. But I just thought it could be simpler to get an overview from the root folder then.

2021-01-13 11:45 UTC, nicholasdalhaug commented on pipelines/deploy-fusion-prod.yml
> +# Deploy fusion-bmt to prod environment
Will you change the reference to these files as well, so they are used correctly by pipelines and radix? I am thinking about the moving to the `pipelines` folder.

2021-01-13 11:45 UTC, nicholasdalhaug commented on pipelines/deploy-fusion-prod.yml
> +          workingDir: 'frontend'
```suggestion
      - task: Npm@1
        displayName: 'Install frontend'
        inputs:
          command: 'install'
          workingDir: 'frontend'
```

2021-01-13 11:45 UTC, nicholasdalhaug commented on pipelines/deploy-fusion-prod.yml
> +          tokenResource: '97978493-9777-4d48-b38a-67b0b9cd88d2'
Is this a secret?

2021-01-13 11:45 UTC, nicholasdalhaug commented on pipelines/deploy-fusion-prod.yml
> +          action: 'Publish'
What is the difference between the Deploy and the Publish?

2021-01-13 12:37 UTC, ReedOnly commented on pipelines/deploy-fusion-prod.yml
> +# Deploy fusion-bmt to prod environment
yup, will update after merging 👍

2021-01-13 12:38 UTC, ReedOnly commented on pipelines/deploy-fusion-prod.yml
> +          tokenResource: '97978493-9777-4d48-b38a-67b0b9cd88d2'
nope, is just uuid of ad group

2021-01-13 12:38 UTC, ReedOnly commented on pipelines/deploy-fusion-prod.yml
> +          action: 'Publish'
you can deploy without actually making visible in the portal. No idea, why its possible btw 😄

2021-01-13 14:50 UTC, nicholasdalhaug approved these changes

2021-01-13 14:53 UTC, merged