[WIP] Frontend: Create View for Edit Action sidebar component #209
equinor/fusion-bmt pull request #268
Opened 2021-01-11 08:59 UTC by denektenina

2021-01-12 14:26 UTC, ReedOnly approved these changes
Component looks good, and works locally!

2021-01-12 15:48 UTC, nicholasdalhaug requested changes
You have some nice solutions here that I think we should have used some other places as well, but we can take those as we see fit. I have some comments, and I would like to discuss them as well. 

Not least, could we discuss wether or not to create a totally new sidebar? I think we can avoid some checks at least, and some props. Especially when we start having the possibility to edit actions where there is not possibility to add actions, I think it could be valuable to have a component for just editing an action. Of course, it would give some copy-paste-code, which is really bad. But let us discuss it!

2021-01-12 15:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/QuestionActionsList.tsx
> +`
This would look better if we just used `<Typography link>...`

2021-01-12 15:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/QuestionActionsList.tsx
> +        actionToEdit && setActionToEdit(undefined)
I cannot remember having seen this used like this before, cool! But I find it more readable and explicit like this: 
```suggestion
        if (actionToEdit !== undefined) {
            setActionToEdit(undefined)
        }
```

I wanted to say that, but if you like that better I might develop a more pronounced preference later.

2021-01-12 15:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +    float: right;
We have earlier used MUI Box with flex, but this seems better 👍

2021-01-12 15:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +const ErrorIconComponent = <Icon size={16} data={error_filled} color="danger" />
I know it might have been there already, but maybe: 

```suggestion
const ErrorIcon = <Icon size={16} data={error_filled} color="danger" />
```

2021-01-12 15:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +    action: Action | undefined
I know they are equivalent, but: 
```suggestion
    action?: Action
```

2021-01-12 15:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +    const [note, setNote] = useState<string>('')
```suggestion
    const [noteInProgress, setNoteInProgress] = useState<string>('')
```

2021-01-12 15:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +    const isEditMode = action && action.id
```suggestion
    const isEditMode = action !== undefined
```

2021-01-12 15:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +    const createdDate = action && action.createDate && new Date(action.createDate).toLocaleString('en-GB').split(',')[0]
```suggestion
    const createdDateString = new Date(action?.createDate).toLocaleString('en-GB').split(',')[0]
```

2021-01-12 15:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +                            <ActionNotesList />
This should be used. And if dummy data is needed, I think it should be placed higher in the hierarchy.

2021-01-12 15:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionNotesList.tsx
> +]
I think this should be place higher in the react hierarchy. This component could actually be finished in this PR. 

```suggestion
const notes: Note[] = [
    {
        id: 'hfjkhfkf78f6s9fhj',
        writerName: 'Anna Therese Asheim',
        message: 'Kan du se på dette Andreas Rønning?',
        date: '2021-01-10T11:27:08.024+01:00',
    },
]
```

2021-01-12 15:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionNotesList.tsx
> +                const minutes = dateAndTime[1].split(':')[1]
```suggestion
                const noteDate = new Date(note.date)
                
                const date = noteDate.getDate()
                const hour = noteDate.getHours()
                const minutes = noteDate.getMinutes()
```

If we set the types right for the component, we can avoid the `note && note.date &&`.

2021-01-12 16:23 UTC, denektenina commented on frontend/src/components/Action/QuestionActionsList.tsx
> +        actionToEdit && setActionToEdit(undefined)
Thanks, I agree! I like to use this notation when I check for presence before using an attribute on an object, but in this case, since it's actually checking if it should perform an action, it's better to use the explicit way.

Also, I just found that the way I normally use it (`user && user.name` for instance), can be better written like user?.name, which is pretty cool :) (more info [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining))

2021-01-12 16:27 UTC, denektenina commented on frontend/src/components/Action/QuestionActionsList.tsx
> +`
lol, I didn't know about that. Will fix!

2021-01-12 16:47 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +    float: right;
In general I prefer being consistent (by using Box since we are using it other places), but in this case it seemed that I had to add additional styling anyways to get the switch all the way to the end, so I ended up with this.

2021-01-12 16:48 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +const ErrorIconComponent = <Icon size={16} data={error_filled} color="danger" />
Yeah, it was there already but I can change it

2021-01-12 16:49 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +    action: Action | undefined
Yes, that's a lot better. Not quite used to typescript yet! Will fix.

2021-01-12 16:51 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +    const [note, setNote] = useState<string>('')
Will fix

2021-01-12 16:53 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +    const isEditMode = action && action.id
Here I'm actually checking for id because I'm thinking it could maybe exist as an object even though it has not been saved to the database and thus not been given an ID.

2021-01-12 16:54 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +    const createdDate = action && action.createDate && new Date(action.createDate).toLocaleString('en-GB').split(',')[0]
Why do we have to include the type in the name here?

2021-01-12 16:55 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +                            <ActionNotesList />
What do you mean?

2021-01-12 16:56 UTC, denektenina commented on frontend/src/components/Action/ActionNotesList.tsx
> +]
I can make the changes but I assume I have to tweak it when connecting to the db since I don't know the real property names.

2021-01-12 16:57 UTC, denektenina commented on frontend/src/components/Action/ActionNotesList.tsx
> +]
What do you mean by higher in the react hierarchy? In the file tree?

2021-01-13 07:24 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +    const isEditMode = action && action.id
That is something that is easier to see if the create and edit action forms were separate. But I think it is safe to say that if the action is not undefined, it will have an id. Otherwise, there is an action in the database with no id, and that is an invalid state. For the action creation, we have no need for this `action` prop.

2021-01-13 07:26 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +    const createdDate = action && action.createDate && new Date(action.createDate).toLocaleString('en-GB').split(',')[0]
Well, we do not have to. But when I read it, I thought it was a date, which it is not, it is a string. `createdDate` sounds like it is a date. On the other hand, the js `Date` is inconsistent on this since if you call `Date.getDate` you get the date number, not all the content of the date object. Could we just do `new Date(action?.createDate).getDate()`?

2021-01-13 07:27 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +                            <ActionNotesList />
```suggestion
                            <ActionNotesList notes={action.notes} />
```

2021-01-13 07:28 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionNotesList.tsx
> +]
Yes, in the file tree. You can find the real property names in `frontend/src/api/models.ts`.

2021-01-13 07:50 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +    const isEditMode = action && action.id
Yeah it's a habit from coding forms earlier. Often you would for instance make an empty object and work with that before saving, and then the only thing that separates a saved and new object is whether or not it has been sent to the db and thus been given an Id. But since we are using state for the attributes before saving here we can use your way. Anyways, I guess the new form-or not thing is something for the later discussion? I don't mind changing it if we decide it's the best :)

2021-01-13 07:58 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +    const createdDate = action && action.createDate && new Date(action.createDate).toLocaleString('en-GB').split(',')[0]
I split the string to omit the time and only keep the date. It is possible to get each of the components of the date (like month, day and year) from the Date object of course, but since the GB-way of formatting was so close to what we needed I thought it was the best way of doing it. I can include string in the name if you feel it makes it easier to understand the code.

2021-01-13 07:59 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +                            <ActionNotesList />
Yes, I will fix rest of the notes-things when I implement the backend functionality. This was just for the view.

2021-01-13 08:00 UTC, denektenina commented on frontend/src/components/Action/ActionNotesList.tsx
> +]
I started on this but it requires some more work than just selecting two different property names (because of the Notes type). It's not a big job, but I might as well do it when I start digging into the Notes-universe in the next task later today.

2021-01-13 08:01 UTC, denektenina commented on frontend/src/components/Action/ActionNotesList.tsx
> +                const minutes = dateAndTime[1].split(':')[1]
If it's ok with you I will also fix this as part of the  other task

2021-01-13 09:59 UTC, nicholasdalhaug approved these changes

2021-01-13 10:38 UTC, merged