Rename steps in an evaluation
equinor/fusion-bmt pull request #272
Opened 2021-01-11 14:32 UTC by ReedOnly

- Hard code backend url for compatibility
- Rename Preparation -> Individual Assessment
- Rename Alignment -> Preparation
- rename Workshop -> Workshop Aassessment

closes #267

2021-01-11 14:36 UTC, ReedOnly commented
I did not rename Workshop" to "WorkshopAssessment" in all the files and variables, maybe we should?

2021-01-11 15:30 UTC, nicholasdalhaug reviewed
Could we just use `Individual` instead of `IndividualAssessment`? I think we should ask Benjamin about some of this stuff. Also, this PR should not be merged before the database is updated / nuked.

2021-01-13 14:55 UTC, ReedOnly commented on frontend/src/components/AnswerSummarySidebar.tsx
> +    const IndividualAnswers = answers.filter(a => a.progression === Progression.Individual)
Should this start with capital letter or not?

2021-01-13 14:57 UTC, nicholasdalhaug commented on frontend/src/components/AnswerSummarySidebar.tsx
> +    const IndividualAnswers = answers.filter(a => a.progression === Progression.Individual)
I think variable names should start with a lower-case letter.

2021-01-14 07:32 UTC, Christdej requested changes
Good good, remember to update the DB and Codacy had some notes I would consider fixing

2021-01-14 07:32 UTC, Christdej commented on backend/api/Models/Models.cs
> +        public ActiveStatus ActiveStatus { get; set; }
We already have a enum called status, use that

2021-01-14 07:32 UTC, Christdej commented on backend/api/Startup.cs
> +            // app.UseAuthorization();
Uncomment this

2021-01-14 07:50 UTC, nicholasdalhaug commented on backend/api/Models/Models.cs
> +        public ActiveStatus ActiveStatus { get; set; }
This was actually my suggestion. I think this is a renaming of the old `Status`. I thought that `Status` was actually not very descriptive.

2021-01-14 07:55 UTC, Christdej commented on backend/api/Models/Models.cs
> +        public ActiveStatus ActiveStatus { get; set; }
What about a boolean value called Active?

2021-01-14 07:57 UTC, nicholasdalhaug requested changes

2021-01-14 07:57 UTC, nicholasdalhaug commented on backend/api/Models/Models.cs
> +        public ActiveStatus ActiveStatus { get; set; }
But shouldn't that renaming also be in this file? I cannot see it.

2021-01-14 07:57 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/EvaluationView.tsx
> +                title="Individual Assessment"
Here and on the lines below we can use the function `progressionToString(...)`.

2021-01-14 07:57 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/Preparation/PreparationView.tsx
> +                            open={selectedQuestion != undefined}
```suggestion
                            open={selectedQuestion !== undefined}
```

2021-01-14 08:53 UTC, ReedOnly commented on frontend/src/views/Evaluation/Preparation/PreparationView.tsx
> +                            open={selectedQuestion != undefined}
fixed!

2021-01-14 08:53 UTC, ReedOnly commented on frontend/src/views/Evaluation/EvaluationView.tsx
> +                title="Individual Assessment"
fixed!

2021-01-14 09:46 UTC, Christdej approved these changes

2021-01-14 09:48 UTC, nicholasdalhaug approved these changes

2021-01-14 09:48 UTC, merged