[WIP]: Created mutation for editing action and tied it together with complete button tamporarily
equinor/fusion-bmt pull request #294
Opened 2021-01-14 15:44 UTC by denektenina

2021-01-19 16:40 UTC, nicholasdalhaug reviewed
For some reason, all my comments on earlier commits have disappeared. I will come back to this PR later.

2021-01-19 16:40 UTC, nicholasdalhaug commented on frontend/package-lock.json
> +        },
Why did the package-lock change? Just wondering since we do not want to change it back and forth.

2021-01-19 16:40 UTC, nicholasdalhaug commented on frontend/src/api/fragments.ts
> +        }
I do not think we should have the whole action available on all notes. Consider just adding it to the mutation later.

2021-01-19 16:40 UTC, nicholasdalhaug commented on frontend/src/api/mutations.ts
> +    createNote: (data: DataToCreateNote) => void
I understand we did this in the same way as above, but we have mostly been using simple arguments. Then we do not have to create objects and pass them in, only fill out the arguments. Like this: 
`createNote: (actionId: string, text: string) => void`

2021-01-19 16:40 UTC, nicholasdalhaug commented on frontend/src/api/mutations.ts
> +                ...NoteFields
Since the mutation wants the action id of the note, it makes sense to ask for that here: 
`action { id }`

2021-01-19 16:40 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +`
If the Icon should be clickable, could we not just make it a button with an Icon in? I believe we have done that other places.

2021-01-19 16:40 UTC, nicholasdalhaug commented on frontend/src/components/Action/QuestionActionsList.tsx
> +            setActionToEditId(undefined)
Would it make more sense to just set it to undefined anyways? Or maybe it makes it less understandable? I just think it would be nice to not have to understand the if-statement.

2021-01-19 16:40 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +    }, [title, description])
Consider making this into our own hook so it is easier to reuse. I believe this is reused in part from Q&A form, but also saves on mount.

2021-01-19 16:40 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +    }, [assignedTo, onHold, dueDate, priority, completed])
Consider not saving on mount

2021-01-19 16:40 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +                                enterKeyHint=""
I guess the comment should be here as well: `// This is required to avoid an error`

2021-01-20 07:59 UTC, nicholasdalhaug requested changes
I realised in the middle of this that this PR should probably be squashed. 

I ran the code and the page looks really good!

2021-01-20 07:59 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
>              autosaveChanges()
See Codacy

2021-01-20 07:59 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +                                        e.preventDefault()
Should this be added in the earlier commit?

2021-01-20 07:59 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +
Should this be added in the earlier commit?

2021-01-20 07:59 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionNotesList.tsx
> +    const sorted = notes.slice().sort((a, b) => {
`sortedNotes` maybe. A bit more readable I think.

2021-01-20 09:38 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +            const actionData: Action = {
But it's not a new action, right? It's just the data for updating the existing action?

2021-01-20 09:39 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +                completed: false, // TODO: This is still to be decided
This is now fixed (I'm now updating with autosave, so clicking complete (which is now a switch and not a button), will set completed to true or false, depending on the previous value)

2021-01-20 09:41 UTC, denektenina commented on frontend/package-lock.json
> +        },
True. I think it happened because I ran npm install after having pulled, or maybe when I installed the project on my new mac. Don't know why this was updated for me first though. I have not installed anything new. Was unsure if I should commit this file. Do you want me to remove it from the PR?

2021-01-20 09:45 UTC, denektenina commented on frontend/src/api/fragments.ts
> +        }
Will just add action id then.

2021-01-20 10:06 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +            const actionData: Action = {
´editedAction`?

2021-01-20 10:09 UTC, nicholasdalhaug commented on frontend/package-lock.json
> +        },
I just checked and I get the same here. Then I think it will not change all the time and we should keep it.

2021-01-20 10:12 UTC, denektenina commented on frontend/src/api/mutations.ts
> +    createNote: (data: DataToCreateNote) => void
Will fix

2021-01-20 10:18 UTC, denektenina commented on frontend/src/api/mutations.ts
> +                ...NoteFields
Will fix

2021-01-20 10:51 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +`
Good idea! Will fix

2021-01-20 10:52 UTC, denektenina commented on frontend/src/components/Action/QuestionActionsList.tsx
> +            setActionToEditId(undefined)
I guess it wouldn't make a practical difference, so I can do that

2021-01-20 10:53 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +    }, [title, description])
As discussed, we will fix this when your code is ready

2021-01-20 10:53 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +    }, [assignedTo, onHold, dueDate, priority, completed])
Have fixed

2021-01-20 10:54 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +                                enterKeyHint=""
Fixed

2021-01-20 11:09 UTC, denektenina commented on frontend/src/components/Action/ActionNotesList.tsx
> +    const sorted = notes.slice().sort((a, b) => {
Fixed

2021-01-20 11:12 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +            const actionData: Action = {
Ok will fix this and the create Action function above (with newAction)

2021-01-20 11:38 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
>              autosaveChanges()
Is it not a problem since it is only run after mount?

2021-01-20 11:46 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +                                enterKeyHint=""
Are you sure? 
```suggestion
                                enterKeyHint="" // This is required to avoid an error
```

2021-01-20 12:05 UTC, nicholasdalhaug approved these changes

2021-01-20 12:09 UTC, merged