[WIP] Save indicator
equinor/fusion-bmt pull request #312
Opened 2021-01-19 17:11 UTC by denektenina

2021-01-21 08:49 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +`
I still think this could be placed as its own component. 

The `SmallCircularProgress` I can understand, even though I am not sure if it is necessary to move the styling to the top of the file. But the other components  here I do not see how that the names imply the styling, what type of components they are based on the name nor why they are placed at the top of the file. The code would be easier to read if the padding for example is simply placed in the Typography where it is used. 

Also, is it necessary to specify top and right here? That sounds like styling based on the use of the component and not styling for the component itself. 

Should we use `rem` instead of `px`?

2021-01-21 08:49 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +
This could be a typescript enum. And I think we should name them with PascalCasing, eg. `Saving`.

2021-01-21 08:49 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +    actionIsSaving: boolean
I would call it `isActionSaving`, but do you think this is better? I find it easier to know exactly what it is when it starts with "is". Then I immediately see it is a boolean and can read the rest of the name to see what it represents. `actionIsSaving` sounds like a statement to me and I have to think a bit. But I think it sounds better in an if-statement: `if (actionIsSaving) {`.

2021-01-21 08:49 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +
Maybe call the enum `SavingStates` since it is not a state but rather all the possible states? Or maybe it is good when `savingState` is an implementation of `SavingState`, not sure.

2021-01-21 08:49 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +
If you time this perfectly, I think you can get a situation where it says "Saved" right after you write and while it is saving. This is because the timeout does not check if it is still not saving after 1 second. Right? I think it can be fixed with a cleanup function in the useEffect.

2021-01-21 08:49 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +                            setSavingState(SavingState.SAVING)
We do not need to set saving state on different fields. It is set by the input variable `isActionSaving`.

2021-01-21 16:18 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +
True. I suggest we remove it. It's not a big problem, it seems to end up with the correct confirmation after having flashed through an extra status, but since it's unpredictable and not completely necessary, I suggest we just keep the saved-icon to confirm to the user that the action is saved after changes.

2021-01-22 08:48 UTC, nicholasdalhaug requested changes

2021-01-22 08:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +    setSavingState: (savingState: number) => void
I do not think the form need to know about the saving states. Could we just have a function `onErrorValidity` or something?

2021-01-22 08:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +            setSavingState(SavingState.None)
```suggestion
            onErrorValidity()
```

2021-01-22 08:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +                        }}
```suggestion
                        onChange={(event: TextFieldChangeEvent) => {
                            setTitle(event.target.value)
                        }}
```

2021-01-22 08:48 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +                        }}
When saving can be figured out on the outside of this component, maybe in the `onActionEdit` function.

2021-01-22 08:48 UTC, nicholasdalhaug commented on frontend/src/components/SaveIndicator.tsx
> +    setSavingState: (savingState: number) => void
```suggestion
    savingState: SavingState
    setSavingState: (savingState: SavingState) => void
```

2021-01-22 08:48 UTC, nicholasdalhaug commented on frontend/src/components/SaveIndicator.tsx
> +    }, [isSaving])
It seems for me like there is a spread of responsibilities here. I think this component does not need to change the saving state. It takes in a saving state and displays the correct content. Deciding what that saving state is could be done on the outside, instead of both outside and inside this component.

2021-01-22 08:49 UTC, nicholasdalhaug commented on frontend/src/components/SaveIndicator.tsx
> +                    <CircularProgress style={{ width: '25px', height: '25px' }}></CircularProgress>
```suggestion
                    <CircularProgress style={{ width: '25px', height: '25px' }} />
```

2021-01-22 08:52 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +
Agreed

2021-01-22 08:56 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +                        }}
Sorry, this is to make it say "Saving" before the actual call to the api, during the 1s delay.

2021-01-22 08:58 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +            setSavingState(SavingState.None)
Yes, that's probably better!

2021-01-22 09:11 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +`
This is fixed by making new component and moving some of the styling to the tags. Have not changed to rem, but is it any point since we are using px other places?

2021-01-22 10:08 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +    setSavingState: (savingState: number) => void
I think this is difficult to fix without splitting edit and create form

2021-01-22 10:09 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +            setSavingState(SavingState.None)
Well, we still need the setSavingState to run to get the "Saving" before the edit call is done. So I think this should not be done. 
I think this is difficult to fix without splitting edit and create form

2021-01-22 10:09 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +                        }}
I think this is difficult to fix without splitting edit and create form

2021-01-22 10:10 UTC, nicholasdalhaug commented on frontend/src/components/Action/ActionForm.tsx
> +`
Yes, I think we might want to change it the other placed as well 😊

2021-01-22 10:17 UTC, denektenina commented on frontend/src/components/Action/ActionForm.tsx
> +`
Ok. Then resolve maybe?

2021-01-22 10:20 UTC, denektenina commented on frontend/src/components/SaveIndicator.tsx
> +    }, [isSaving])
Ok, yeah, I agree that it's not ideal to do it both places. Only thing is that this code is a bit ugly and would be good to hide one place instead of repeating throughout the application

2021-01-22 15:44 UTC, nicholasdalhaug approved these changes

2021-01-22 16:01 UTC, merged