Add health endpoint to check if backend and db is running
equinor/fusion-bmt pull request #326
Opened 2021-01-21 12:34 UTC by ReedOnly

closes #325

2021-01-21 12:37 UTC, Christdej requested changes

2021-01-21 12:37 UTC, Christdej commented on backend/api/Startup.cs
> +            services.AddApplicationInsightsTelemetry();
ApplicationInsight is added in Program.cs, is this needed?

2021-01-21 12:53 UTC, nicholasdalhaug reviewed
Have you checked if this gives an error for the case of unfit database to the models used?

2021-01-21 13:14 UTC, ReedOnly commented on backend/api/Startup.cs
> +            services.AddApplicationInsightsTelemetry();
This will give more metrics as well, not only the logs

2021-01-21 13:31 UTC, ReedOnly commented
It gives error when database is down, but not if it is missing a migration. The problem is also that not all migrations make changes that will be affected by a particular test querying the db.

2021-01-21 13:52 UTC, Christdej commented on backend/api/Startup.cs
> +            services.AddApplicationInsightsTelemetry();
As long as it does not add noise to the logs Im happy

2021-01-22 07:40 UTC, nicholasdalhaug approved these changes

2021-01-22 11:49 UTC, ReedOnly commented on backend/api/Startup.cs
> -                services.AddDbContext<BmtDbContext>(options => options.UseSqlServer(_sqlConnectionString, o => o.UseQuerySplittingBehavior(QuerySplittingBehavior.SingleQuery)));
I simplified this and added Transient lifetime for db connection, in order to do polling for health check. Is there any reason we needed the querySPlittingBehaviour?

2021-01-22 11:52 UTC, Christdej commented on backend/api/Startup.cs
> -                services.AddDbContext<BmtDbContext>(options => options.UseSqlServer(_sqlConnectionString, o => o.UseQuerySplittingBehavior(QuerySplittingBehavior.SingleQuery)));
This was a bug that was introduced in HotChocolate v5, It look like they have fixed in 5.0.2, will dobbel check

2021-01-22 11:56 UTC, Christdej requested changes

2021-01-22 11:56 UTC, Christdej commented on backend/api/Startup.cs
> +            services.AddHealthChecks().AddCheck<GraphQuery>("GraphQl");
Rename the healthcheck to "ModelsFromDB" or something I think, because this is not actually checking GraphQL, but rather that we can retrieve values from the DB and turn them into models

2021-01-22 11:56 UTC, Christdej commented on backend/api/GQL/Query.cs
> +        public Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default)
I think the interface allows us to not take HealthCheckContext as a parameter, so make Codacy happy

2021-01-22 11:56 UTC, Christdej commented on backend/api/GQL/Query.cs
> +                Evaluation evaluation = _evaluationService.GetAll().First();
Check if it is possible to only do:
_evaluationService.GetAll().First();
(remove the left side of the equal sign)
to see if this still fails on the test db, no need to assign to a variable if we dont use it

2021-01-22 14:41 UTC, nicholasdalhaug commented on backend/api/.editorconfig
> +dotnet_diagnostic.ASP0001.severity = none
Why do we not want to have this warning? Why not just move the `useAuthorization`?

2021-01-22 14:41 UTC, nicholasdalhaug commented on backend/api/Startup.cs
> -                services.AddDbContext<BmtDbContext>(options => options.UseSqlServer(_sqlConnectionString, o => o.UseQuerySplittingBehavior(QuerySplittingBehavior.SingleQuery)));
Is the querysplitting behaviour fixed? And what does transient lifetime mean? I thought the connection had to be up at all times for sqlite?

2021-01-22 14:41 UTC, nicholasdalhaug commented on backend/api/Startup.cs
> +            });
Are we creating endpoints without authorization? Is that safe?

2021-01-22 14:42 UTC, ReedOnly commented on backend/api/.editorconfig
> +dotnet_diagnostic.ASP0001.severity = none
because we dont want to have auth on the /health endpoint

2021-01-22 15:17 UTC, ReedOnly commented on backend/api/Startup.cs
> -                services.AddDbContext<BmtDbContext>(options => options.UseSqlServer(_sqlConnectionString, o => o.UseQuerySplittingBehavior(QuerySplittingBehavior.SingleQuery)));
No, still not fixed

2021-01-22 15:24 UTC, nicholasdalhaug approved these changes

2021-01-22 15:30 UTC, merged