[WIP] Spinner when saving in questions form
equinor/fusion-bmt pull request #340
Opened 2021-01-25 09:03 UTC by denektenina

2021-01-25 15:15 UTC, nicholasdalhaug requested changes
Some thoughts

2021-01-25 15:15 UTC, nicholasdalhaug commented on frontend/src/components/QuestionAndAnswer/AnswerMarkdownForm.tsx
> +    setSavingState: (savingState: SavingState) => void
I do not think this should be relevant for the markdown form. It has no need of knowing about the saving state.

2021-01-25 15:15 UTC, nicholasdalhaug commented on frontend/src/components/QuestionAndAnswer/QuestionAndAnswerForm.tsx
> +
How about this component taking as input the saving state and displays it correctly? The nwe can move this useEffect and the timing useEffect to the component above in the hierarchy.

2021-01-25 15:15 UTC, nicholasdalhaug commented on frontend/src/components/QuestionAndAnswer/QuestionAndAnswerForm.tsx
> +                        </Box>
Saving a little margin by only specifying the right-margin and save some code by moving the centering up. 
```suggestion
                        <Box display="flex" justifyContent="flex-end" alignItems="center">
                        <Box mr={1}>
                            <SaveIndicator savingState={savingState} />
                        </Box>
                        <Chip primary title={organizationToString(question.organization)} />
                    </Box>
```

2021-01-25 16:09 UTC, denektenina commented on frontend/src/components/QuestionAndAnswer/AnswerMarkdownForm.tsx
> +    setSavingState: (savingState: SavingState) => void
Fixing

2021-01-25 16:27 UTC, denektenina commented on frontend/src/components/QuestionAndAnswer/QuestionAndAnswerForm.tsx
> +
Sure, will fix

2021-01-25 16:27 UTC, denektenina commented on frontend/src/components/QuestionAndAnswer/QuestionAndAnswerForm.tsx
> +                        </Box>
Agreed, but increasing the right-margin then, because I think it was a little too close with only 8px

2021-01-26 08:33 UTC, nicholasdalhaug requested changes

2021-01-26 08:33 UTC, nicholasdalhaug commented on frontend/src/components/QuestionAndAnswer/AnswerMarkdownForm.tsx
> +import { SavingState } from '../../utils/Variables'
Not used

2021-01-26 08:33 UTC, nicholasdalhaug commented on frontend/src/components/QuestionAndAnswer/QuestionAndAnswerForm.tsx
> +                                        setSavingState(SavingState.Saving)
I though we were to move the timeout out of this to the component above, removing the need for the `setSavingState`?

2021-01-26 08:33 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/Workshop/WorkshopView.tsx
> -import { Barrier, Evaluation, Question, Progression, Role } from '../../../api/models'
Maybe not reorder this in this PR?

2021-01-26 08:57 UTC, denektenina commented on frontend/src/components/QuestionAndAnswer/QuestionAndAnswerForm.tsx
> +                                        setSavingState(SavingState.Saving)
I moved it one step up, but we need it where the question is answered if we want it to change state to Saving while writing

2021-01-26 08:57 UTC, denektenina commented on frontend/src/views/Evaluation/Workshop/WorkshopView.tsx
> -import { Barrier, Evaluation, Question, Progression, Role } from '../../../api/models'
It was prettier xD Do you want me to manually override?

2021-01-26 09:00 UTC, denektenina commented on frontend/src/components/QuestionAndAnswer/AnswerMarkdownForm.tsx
> +import { SavingState } from '../../utils/Variables'
Removing

2021-01-26 09:02 UTC, nicholasdalhaug commented on frontend/src/components/QuestionAndAnswer/QuestionAndAnswerForm.tsx
> +                                        setSavingState(SavingState.Saving)
If we move the other useEffect out as well, we can move the setSavingState out as well.

2021-01-26 09:02 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/Workshop/WorkshopView.tsx
> -import { Barrier, Evaluation, Question, Progression, Role } from '../../../api/models'
Nah, np.

2021-01-26 10:17 UTC, nicholasdalhaug approved these changes

2021-01-26 10:18 UTC, merged