Order question
equinor/fusion-bmt pull request #360
Opened 2021-01-28 13:56 UTC by Christdej

Closes #286 
Closes #108

2021-02-09 08:45 UTC, nicholasdalhaug requested changes
Looks good! I just had one thing that looked like a potential error. Maybe we should have a test for that small edge case.

2021-02-09 08:45 UTC, nicholasdalhaug commented on backend/api/Services/QuestionTemplateService.cs
> +            }
I am guessing this would give an error on the line above if the if is true. 

```suggestion
            int newOrder;
            if (newNextQuestionTemplate.Equals(null))
            {
                newOrder = _context.QuestionTemplates.Max(qt => qt.Order);
            }
            else 
            {
                newOrder = newNextQuestionTemplate.Order - 1;
            }
```

2021-02-09 08:45 UTC, nicholasdalhaug commented on backend/tests/Services/QuestionTemplateService.cs
> +            int prevOrder = questionTemplate.Order;
Maybe use `prevOrder`?

2021-02-09 09:48 UTC, Christdej reviewed
Make migration and add to PR

2021-02-09 11:31 UTC, ReedOnly commented
The migration we remove, should weremove it from git is this pr as well, or wait until after db update is completed?

2021-02-09 13:56 UTC, Christdej commented on backend/api/Services/QuestionTemplateService.cs
> +            }
yes, fixed

2021-02-09 13:56 UTC, Christdej commented on backend/tests/Services/QuestionTemplateService.cs
> +            int prevOrder = questionTemplate.Order;
removed

2021-02-10 08:16 UTC, ReedOnly approved these changes

2021-02-10 10:55 UTC, ReedOnly approved these changes

2021-02-10 10:59 UTC, merged