[WIP] Made view for actions list
equinor/fusion-bmt pull request #364
Opened 2021-01-29 14:20 UTC by denektenina

2021-02-11 10:23 UTC, nicholasdalhaug requested changes
Remove empty file "ActionSidebar.tsx"

I see that the commits should be squashed. What will be the commit message?

2021-02-11 10:23 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/FollowUp/ActionList.tsx
> +import React, { useEffect, useState } from 'react'
Shouldn't this file be in "components". It will be reused later, so I think it should be reusable.

2021-02-11 10:23 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/FollowUp/ActionList.tsx
> +}
I am pretty sure that the action list only should take in actions and list them. I do not see why the actions list itself would extract actions from an evaluation.

2021-02-11 10:23 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/FollowUp/ActionList.tsx
> +    }
Isn't this just a copy of other code we have?

2021-02-11 10:23 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/FollowUp/ActionList.tsx
> +    useEffect(() => {
Consider using `useMemo` instead.

2021-02-11 10:23 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/FollowUp/ActionList.tsx
> +    }, [sortDirection, columnToSortBy])
Not `actions`?

2021-02-11 10:23 UTC, nicholasdalhaug commented on frontend/src/utils/sort.ts
> +export const sort = (a: string, b: string, sortDirection: SortDirection) => {
```suggestion
export const sortString = (a: string, b: string, sortDirection: SortDirection) => {
```

Or include number, boolean, etc. as input types.

2021-02-11 10:23 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/FollowUp/ActionList.tsx
> +type ColumnType = {
```suggestion
type Column = {
```

2021-02-11 10:23 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/FollowUp/ActionList.tsx
> +        if (columnToSortBy) {
What does this mean? Can it be undefined?

2021-02-11 10:23 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/FollowUp/ActionList.tsx
> +                            return sortPriority(a[accessor], b[accessor], sortDirection)
You do not need to use `accessor` when you know it is `priority`.

2021-02-11 10:23 UTC, nicholasdalhaug commented on frontend/src/views/Project/ProjectRoute.tsx
> -                </Tab>
Maybe remove archive as well?

2021-02-11 10:26 UTC, denektenina commented on frontend/src/utils/sort.ts
> +export const sort = (a: string, b: string, sortDirection: SortDirection) => {
good point, will put number and boolean as input types

2021-02-12 10:26 UTC, denektenina commented on frontend/src/utils/sort.ts
> +}
fixed

2021-02-12 16:17 UTC, denektenina commented on frontend/src/views/Evaluation/FollowUp/ActionList.tsx
> +    }
Fixed by making a hook that all three components are now using

2021-02-12 16:17 UTC, denektenina commented on frontend/src/views/Evaluation/FollowUp/ActionList.tsx
> +    useEffect(() => {
done

2021-02-12 16:17 UTC, denektenina commented on frontend/src/views/Evaluation/FollowUp/ActionList.tsx
> +    }, [sortDirection, columnToSortBy])
fixed by using useMemo and including action there

2021-02-15 10:05 UTC, nicholasdalhaug requested changes

2021-02-15 10:05 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/FollowUp/SortableHeadCell.tsx
> +import React from 'react'
Consider moving into ActionTable component

2021-02-17 14:00 UTC, nicholasdalhaug approved these changes

2021-02-17 14:11 UTC, merged