Ordered questions by new order-attribute on question
equinor/fusion-bmt pull request #383
Opened 2021-02-11 10:45 UTC by denektenina

2021-02-16 13:37 UTC, nicholasdalhaug requested changes

2021-02-16 13:37 UTC, nicholasdalhaug commented on frontend/src/views/Evaluation/Individual/IndividualView.tsx
>                      <QuestionsList
Can we simply order them right before they are being used instead, so in the `QuestionsList`?

2021-02-17 15:32 UTC, denektenina commented on frontend/src/views/Evaluation/Individual/IndividualView.tsx
>                      <QuestionsList
Yes, that's better!

2021-02-17 15:44 UTC, nicholasdalhaug approved these changes

2021-02-17 15:47 UTC, merged