Workflow summary for facilitators
equinor/fusion-bmt pull request #452
Opened 2021-06-15 07:57 UTC by ErlendHaa

A couple of points worth nothing:

 - This requires a database migration
 - Currently _only_ the facilitators can modify the summary
 - The summary field is a string on the ``Evaluation``. I.e. we have no timestamps or record of authors. 
 - There is no front-end tests
 - Missing error handling for potential Apollo Errors

Closes #439

2021-06-24 11:56 UTC, maiaht reviewed
Have you set up Prettier for your editor?

2021-07-07 10:13 UTC, ReedOnly commented
This should only be visible for Facilitator and Admin

2021-07-07 10:39 UTC, ReedOnly requested changes
Looks good, but after talking to users, they want that this summary should only be visible for Facilitator and Admin

2021-07-09 13:59 UTC, ReedOnly approved these changes

2021-07-09 14:14 UTC, merged