Optionally add reason when completing action
equinor/fusion-bmt pull request #543
Opened 2021-08-17 14:49 UTC by denektenina

**Context:** Users of BMT have asked for a feature where they can provide a reason when completing an action. Although we have not properly decided how to solve this, this pull request provides a suggestion.

**Solution in steps:**
1) An incomplete action looks like this in the edit action panel:

![image](https://user-images.githubusercontent.com/1130244/129747757-f26d3086-8f0e-456e-b4f3-a2c192c5acb1.png)

2) User clicked "completed"-switch and the action was completed. Optional text field appeared:

![image](https://user-images.githubusercontent.com/1130244/129747860-1cf944dd-6f8a-42e3-908c-e0d11fad901e.png)

3) User entered reason for having completed action. This is saved by pressing enter:

![image](https://user-images.githubusercontent.com/1130244/129747966-6a5d8589-04e3-43c3-b19a-62b48411126a.png)

4) The completed-comment is now saved to notes (see bottom). However, the user regretted their choice and clicked "complete"-switch again to re-open action. Text field now appears again and a new reason is given:

![image](https://user-images.githubusercontent.com/1130244/129748099-23949292-4cab-469f-9b2f-2a6a0b360ac8.png)

5) All completion-texts are saved to notes, giving a nice little log:

![image](https://user-images.githubusercontent.com/1130244/129748192-fe73242d-82ec-4355-8e8d-7da5a39363d1.png)

**Comments / Improvements:** The text field could maybe have an x-icon at the far right so that the user can get rid of the input field if they don't intend to write anything and is annoyed by its presence?

2021-08-31 09:28 UTC, ReedOnly commented
/azp run

2021-09-02 06:56 UTC, petterwildhagen commented on frontend/cypress/integration/actions_spec.ts
> +        it('Action can be completed without writing a reason', () => {
Clarify with customer if this is possible?

2021-09-02 07:02 UTC, denektenina commented on frontend/cypress/integration/actions_spec.ts
> +        it('Action can be completed without writing a reason', () => {
This was possible until yesterday, but now it seems it should be mandatory, so I think I will change it (checking with Andreas first)

2021-09-02 07:11 UTC, petterwildhagen commented on frontend/cypress/integration/actions_spec.ts
> +const createCompleteActionSeed = () => {
Avoid coupling initial state to actual test case. This almost does the same as createEditSeed. It is better to create an evaluation that has actions , k.e. createEvaluationWithSomeActions and pass completeState as optional parameter (if not set randomize as is now) - this can then be used in all testcases, see https://github.com/equinor/fusion-bmt/pull/586

2021-09-02 09:00 UTC, denektenina commented on frontend/cypress/integration/actions_spec.ts
> +const createCompleteActionSeed = () => {
Good point! Fixed now.

2021-09-02 09:07 UTC, maiaht requested changes
The `EvaluationGQL.ts` file is now an empty file, but it should be deleted

2021-09-02 09:07 UTC, maiaht commented on frontend/src/components/ActionTable/ActionTableForOneUserWithApi.tsx
>  }
This should be placed in the bottom of the file

2021-09-02 09:07 UTC, maiaht commented on frontend/src/components/ActionTable/ActionTableForOneUserWithApi.tsx
> -}
This should not be removed, it should be used by the new query

2021-09-02 09:20 UTC, denektenina commented on frontend/src/components/ActionTable/ActionTableForOneUserWithApi.tsx
>  }
Fixed

2021-09-02 09:21 UTC, denektenina commented on frontend/src/components/ActionTable/ActionTableForOneUserWithApi.tsx
> -}
Fixed

2021-09-02 09:35 UTC, petterwildhagen approved these changes
Nice refactoring of setup of initial state.

2021-09-02 09:37 UTC, merged

2021-09-02 14:23 UTC, achaikou reviewed
:snail: [world's fastest delivery service] Review started yesterday has arrived! :snail:
Nothing critical, so just take a look if there is something that is worth fixing in the next PR.

2021-09-10 08:56 UTC, denektenina commented on frontend/src/components/Action/EditForm/ActionEditSidebar.tsx
> +    const notesAndClosingRemarks: (Note | ClosingRemark)[] = action.notes.map(note => note)
Fixed

2021-09-10 08:57 UTC, denektenina commented on frontend/cypress/integration/actions_spec.ts
> +            editActionDialog.completedReasonInput().replace('Closed because of a good reason')
Fixed in new PR (626), I think

2021-09-10 08:57 UTC, denektenina commented on frontend/cypress/support/action.ts
> +    assertNoClosingMessageInNotes = (notes: Note[]) => {
Fixed in new PR (626)

2021-09-10 08:57 UTC, denektenina commented on frontend/src/components/Action/EditForm/ActionEditSidebar.tsx
> +        action.closingRemarks.forEach(closingRemark => {
Fixed in new PR (626)

2021-09-10 08:58 UTC, denektenina commented on frontend/src/components/Action/EditForm/ActionEditForm.tsx
> -    const [onHold, setOnHold] = useState<boolean>(action.onHold)
I guess that's something for the team to discuss

2021-09-10 08:58 UTC, denektenina commented on frontend/src/components/Action/EditForm/ActionEditForm.tsx
> +                            <Typography variant="body_short">This cannot be undone.</Typography>
I guess that's something for the team to discuss

2021-09-10 09:01 UTC, denektenina commented on frontend/src/components/Action/EditForm/ActionEditForm.tsx
> +                                        if (!apiErrorClosingRemark) {
I know, but that's how it is as long as we are using two different API-calls for this. We have also discussed this on of the daylies and decided that this is so unlikely we accept it. But, later I will do a PR for making the closing remark mandatory, and then I will check out the possibility of making a new complete-action-endpoint that requires a closing remark where both operations have to succeed.

2021-09-10 09:03 UTC, denektenina commented on frontend/src/components/Action/EditForm/ActionEditForm.tsx
> +        if (apiErrorAction && completeActionViewOpen) {
Because it was confusing that the view stayed open even though the action is now completed (or something like that). Like I said before and on the daily: It's difficult to make good error handling with two different endpoints.

2021-09-10 09:03 UTC, denektenina commented on frontend/src/components/Action/EditForm/ActionEditForm.tsx
> +                )}
Good catch but I agree that I don't think it will affect anything.

2021-09-10 09:04 UTC, denektenina commented on frontend/cypress/support/mock/external/external.ts
> +    if (err.message.includes("Cannot read properties of null (reading 'removeEventListener')")) {
Submitted twice?

2021-09-10 09:13 UTC, denektenina commented on frontend/cypress/integration/actions_spec.ts
> +        function checkView() {
Fixed in 626 I think.

2021-09-10 09:14 UTC, denektenina commented on frontend/cypress/integration/actions_spec.ts
> +            editActionDialog.actionCompletedText().should('exist')
Changed in 626.

2021-09-10 09:14 UTC, denektenina commented on frontend/cypress/integration/actions_spec.ts
> +            editActionDialog.assertNoClosingMessageInNotes(existingNotes)
Maybe reconsider this in 626? I have made some changes there.

2021-09-10 09:15 UTC, denektenina commented on frontend/cypress/support/action.ts
> +            if (note.text) {
Maybe reconsider this in 626? I have made some changes there.

2021-09-10 09:15 UTC, denektenina commented on frontend/cypress/integration/actions_spec.ts
> +                editActionDialog.assertActionValues(updatedAction, existingNotes.concat([newNote]))
Maybe reconsider this in 626? I have made some changes there.

2021-09-10 09:33 UTC, achaikou commented on frontend/cypress/support/mock/external/external.ts
> +    if (err.message.includes("Cannot read properties of null (reading 'removeEventListener')")) {
https://github.com/equinor/fusion-bmt/blob/72c7e8b93316f6752eecffae86707be78298bb29/frontend/cypress/support/mock/external/external.ts#L127

https://github.com/equinor/fusion-bmt/blob/72c7e8b93316f6752eecffae86707be78298bb29/frontend/cypress/support/mock/external/external.ts#L132