Cypress fixes for contexts call
equinor/fusion-bmt pull request #555
Opened 2021-08-19 16:52 UTC by achaikou

- Fixes actual contexts situation
- Completely disabled the reason that caused the failure. With that there will be no clearly visible error information for us anymore that we are missing some data, so it has to be provided only when actual functionality is tested. This change is also expected to cause better tests stability.

2021-08-19 16:53 UTC, achaikou commented
/azp run

2021-08-20 07:18 UTC, petterwildhagen requested changes

2021-08-20 07:18 UTC, petterwildhagen commented on frontend/cypress/support/mock/external/projects.ts
> + */
If this cannot appear in the real world, why create test data for it?

2021-08-20 08:56 UTC, achaikou commented on frontend/cypress/support/mock/external/projects.ts
> + */
It doesn't mean that it can not. It just means that by analyzing _current_ existing fusion data I found none right now.
But the fields themselves [are](https://github.com/equinor/fusion-functions/blob/master/domains/Fusion.Functions.Context.ContextSync/Models/ProjectFusionContext.cs) [real](https://github.com/equinor/fusion-functions/blob/master/domains/Fusion.Functions.Context.ContextSync/Models/FusionContext.cs). Someone put them there with intention.

Until we get new information, these can be used just as other normal projects (if 3 main ones are not enough for some reason).
I just believed these fields to be interesting enough to create mock objects with them. The same way I created different users for different employee types, thus in theory different privileges.

Meaning that if these interesting fields ever cause any difference in future, we would have a chance to catch it and adjust application logic.

2021-08-20 13:02 UTC, petterwildhagen commented on frontend/cypress/support/mock/external/projects.ts
> + */
If the fields are not used isn't it better to remove them from the application altogether, rather than create testdata for them? It might be 'a bug' that they are there.

2021-08-20 13:03 UTC, achaikou commented on frontend/cypress/support/mock/external/projects.ts
> + */
This is not our code. We have no idea what all the fusion guys plan to do and why they introduced them.

2021-08-23 06:48 UTC, petterwildhagen commented on frontend/cypress/support/mock/external/projects.ts
> + */
The fields are not used in the application. Here is the model for project from frontend/api : export type Project = {
  __typename?: 'Project';
  id: Scalars['String'];
  fusionProjectId: Scalars['String'];
  createDate: Scalars['DateTime'];
  evaluations: Array<Maybe<Evaluation>>;
};  The fields invalid, inactive or deleted  are not present in the model, hence not used in BMT and therefore no testdata needs to or should be created

2021-08-23 16:47 UTC, achaikou commented
/azp run

1. Will handle fixups before merge on rebasing. Due to refactoring they do not align correctly to respective comments.
2. Was able to reproduce both errors that are now handled in `on uncaught exception` and verify that they no longer cause problems with current handling
3. Remaining changes done as per discussion.

2021-08-23 16:47 UTC, achaikou commented
/azp run

2021-08-24 10:35 UTC, petterwildhagen approved these changes

2021-08-24 11:33 UTC, achaikou commented
/azp run

2021-08-24 13:12 UTC, merged